apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnb-pl
  labels:
    app: pnb-pl
spec:
  selector:
    matchLabels:
      app: pnb-pl
  template:
    metadata:
      labels:
        app: pnb-pl
    spec:
      containers:
      - name: pnb-pl
        image: slavicviking/www-pnb
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi
