---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pnb-pl
  labels:
    app: pnb-pl
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: pnb-pl
  targetCPUUtilizationPercentage: 80