apiVersion: v1
kind: Service
metadata:
  name: pnb-pl
  labels:
    app: pnb-pl
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: pnb-pl
